### ISSUE TITLE
s_ntctst::TestUtil?

### ISSUE THREAD

**Issue by michihenning** [bloomberg/ntf-core#17]
In ntci_timer.h, there are several places with this code:
```
///     bsl::shared_ptr<ntci::Timer> timer =
///         s_ntctst::TestUtil::createTimer(timerOptions, timerFuture);
```
I assume that this is a stale example and that the timer should be created by calling Interface::createTimer() instead?

**Comment by mattrm456** [comment]
Yes, this is a stale example. The example should illustrate create the timer using `ntci::Interface::createTimer`. I will create a PR for this.

**Comment by mattrm456** [comment]
Fixed in https://github.com/bloomberg/ntf-core/pull/29
