### ISSUE TITLE
Please support SSM (source specific multicast)

### ISSUE THREAD

**Issue by che2** [bloomberg/ntf-core#193]
Currently 'joinMulticastGroup' only supports 'interface' and 'group' parameters:

```C++
// ntsu_socketoptionutil.h

ntsa::Error SocketOptionUtil::joinMulticastGroup(
    ntsa::Handle           socket,
    const ntsa::IpAddress& interface,
    const ntsa::IpAddress& group)
```
Please add an additional parameter for source address for SSM support.

See:
https://man7.org/linux/man-pages/man7/ip.7.html
IP_ADD_SOURCE_MEMBERSHIP

**Comment by mattrm456** [comment]
Implemented in https://github.com/bloomberg/ntf-core/pull/196
