### ISSUE TITLE
Unimplemented examples and test plan files in the repository

### ISSUE THREAD

**Issue by SoulPancake** [bloomberg/ntf-core#39]
Creating it as an issue, As there is no discussion tab.
I have been studying this repository and noticed that there are numerous files and directories within the examples folder containing empty files or unimplemented examples. Examples include ntcu04.m.cpp, ntcu05.cpp, and so on. Additionally, I've observed some test plan files that seem incomplete.

Is there a roadmap or plan for these files? I am interested in contributing to the development of these examples and test plans. Could someone provide guidance or direction on how to proceed with these unimplemented files? 
Any information or assistance would be greatly appreciated.

**Comment by mattrm456** [comment]
Not all the planned example applications have been implemented, as you've noticed. You can start with a PR to implement ntcu04, which should do what ntsu04 does but with the non-blocking sockets and event loop stuff like in ntcu01.

By incomplete test plans I'm assuming you mean the documentation for test cases where the either the concern is undocumented, or the strategy to test that concern is undocumented. There are many test cases that have one or both those characteristics.  I think the priority should be do first implement the examples with empty `main()`s then you can start by creating an issue (or continuing this one) by proposing specific test driver files that you'd like to contribute changes to.
