### ISSUE TITLE
Issues building ntf-core out-of-the-box

### ISSUE THREAD

**Issue by rdilipk** [bloomberg/ntf-core#5]
A friend who has attempted to build `ntf-core` by following the provided instructions passed this along. While he managed to get past the error, this might be an opportunity to fix the issue at source. Also, he says a couple of tests failed. His platform/toolchain details: `gcc 9.4 on Ubuntu 20.04.`

Here is a private email he sent me:

===========================================================================
I was unable to build ntf-core with bde installed in a non-standard location. I installed bde into /third-party/bde, which was fine. But then trying to configure ntf-core, it kept bombing out looking for bde in /opt/bb, despite having set —prefix. Eventually I gave up and installed bde into /opt/bb. That got me a bit further, but then the build failed with an  error about _FORTIFY_SOURCE being redefined. I ended up having to delete the definition of _FORTIFY_SOURCE in repository.cmake. That allowed my to build.

Running the tests, I get two failures:

The following tests FAILED:
                46 - ntsu_socketutil.t (Subprocess aborted)
                141 - ntcf_system.t (Subprocess aborted)

I ran the tests manually, and got this:

./ntsu_socketutil.t

…
Running test case 13
Running test case 14
Running test case 15
Running test case 16
Running test case 17
[ F ][ 24MAR2023_03:37:58.106 ][             main ][               ntsu_socketutil.t.cpp:5613 ]: Assertion true: context.softwareTimestamp().isNull()
Aborted (core dumped)
 
./ntcf_system.t

...
[ W ][ 24MAR2023_03:39:04.415 ][             main ][                   ntcf_system.t.cpp:7160 ]: ECONNREFUSED/ETIMEDOUT (x5)
Running test case 15
[ W ][ 24MAR2023_03:39:05.117 ][             main ][                   ntcf_system.t.cpp:5519 ]: Testing driver EPOLL (static)
[ W ][ 24MAR2023_03:39:05.117 ][             main ][                   ntcf_system.t.cpp:7280 ]: ETIMEDOUT (x5)
[ F ][ 24MAR2023_03:39:05.134 ][             main ][                   ntcf_system.t.cpp:7333 ]: Assertion failed: connectResult.event().context().error() == ntsa::Error(ntsa::Error::e_CONNECTION_TIMEOUT)
Found:    Connection refused (ECONNREFUSED) (connectResult.event().context().error())
Expected: Connection timed out (ETIMEDOUT) (ntsa::Error(ntsa::Error::e_CONNECTION_TIMEOUT))
Aborted (core dumped)
=========================================================

**Comment by mattrm456** [comment]
For the issue installing BDE into /thirdparty/bde, but the build system thinking that BDE is actually installed into /opt/bb, see https://github.com/bloomberg/bde/issues/290. This appears to be a problem with the build system used by https://github.com/bloomberg/bde: it installed pkgconfig meta-data stating that the "prefix=/opt/bb" regardless of the prefix specified when configuring the build of BDE. I doubled-checked this by building and installing BDE into /thirdparty/BDE, manually fixing-up the pkgconfig meta-data in /thirdparty/bde, then configuring ntf-core with --prefix /thirdparty/bde and I was able to build ntf-core successfully. We'll have to wait for the maintainers of BDE to fix https://github.com/bloomberg/bde/issues/290.

For the remaining issues, I've created three new issues to address them individually:

- For the issue about _FORTIFY_SOURCE, see https://github.com/bloomberg/ntf-core/issues/7
- For the issue wit ntsu_socketutil.t test case 17, see https://github.com/bloomberg/ntf-core/issues/8
- For the issue wit  ntcf_system.t test case 15, see https://github.com/bloomberg/ntf-core/issues/9
