### ISSUE TITLE
Let's add some functionality for convinience of our users

### ISSUE THREAD

**Issue by smtrfnv** [bloomberg/ntf-core#97]
1. Provide a method to concatenate data from multiple `ConstBuffer`s into one char buffer.
`int gather(char* buffer, size_t length, const ConstBuffer* buffers, size_t numBuffers)`

3. Provide methods to append all ntsa buffer types to `bdlbb::Blob`, now there is only `DataUtil::append(bdlbb::Blob *destination, const ntsa::Data& source)` (which requires construction of `ntsa::Data` in advance)

4. Add ability to specify size of `ConstBufferArray` at construction (add `ConstBufferArray(size_t initialSize, bslma::Allocator* basicAllocator = 0)` constructor)

**Comment by mattrm456** [comment]
This has been done.
